### ISSUE TITLE
Setting appropriate flag for pip install

### ISSUE THREAD

**Issue by twinstar26** [IBM/clai#10]
**Describe the bug**
When `install.sh` hits the line `python3 -m pip install -r requirements.txt`, the following pip install error message pops up. `ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.` For my particular case `wrapt` was causing problems but can be any other package.

**To Reproduce**
1. Hit `$ sudo ./install.sh` on terminal.

**shell and OS (please complete the following information):**
 - OS: Linux

**Additional context**
pip cannot properly remove packages installed by "pure" distutils, because distutils doesn't record enough metadata for us to do so. If you installed a package using distutils, you need to manage (and in particular) uninstall it "using distutils". Unfortunately distutils doesn't include an uninstall command, so "uninstall using distutils" means **manually** removing the package.

This issue can be solved by using `--ignore-installed` flag. Some users have also temporarily resolved by using `--user` flag. But `--ignore-installed` worked for me.

**Comment by twinstar26** [comment]
Also I would like to contribute to this project by having this PR.

**Comment by TathagataChakraborti** [comment]
Thanks @twinstar26 for raising this! 👍 💯  

Feel free to raise a PR into `master`, we will review and merge when you have it. Thanks!
