### ISSUE TITLE
Having problems setting up CLAI container in Ubuntu 14.0.4

### ISSUE THREAD

**Issue by sarathsreedharan** [IBM/clai#26]
**Describe the bug**
I am trying to follow the steps mentioned in the README to set up the CLAI container on my Ubuntu 14.0.4 system (Linux en4119722l 4.4.0-75-generic #96~14.04.1-Ubuntu and Docker version 1.6.2, build 7c8fca2), but the command BuildDockerImage.sh is failing while reporting missing flags

**To Reproduce**
```
clai$ sudo ./BuildDockerImage.sh
===============================================================

 Phase 1: Building CLAI Container --no-cache

===============================================================
docker: "build" requires 1 argument. See 'docker build --help'.

real	0m0.016s
user	0m0.016s
sys	0m0.000s
Failed to build CLAI Playground Container. Aborting Build.
```

**Comment by madhavanpallan** [comment]
1) I believe 'clai' setup on the website is on top of Ubuntu (xenial xerus, 4.4.0-173-generic). I also, see most of the tests are run on 'xenial'. Basically, ubuntu 16.04 LTS. I personally tested it on ubuntu 18.04 LTS (Bionic Beaver). I am not sure about backports though.

**Comment by dowem** [comment]
FYI I tried to replicate this today on a couple of different attempts. My only development machine at the moment is a current Mac. I grabbed a vanilla ubuntu 14.04 instance to run in docker on my mac to simulate your host environment. Within that instance, I tried to build clay (with some tricks to get the docker daemon to start from within my ubuntu container such as invoking the docker daemon with no networking as a workaround to make it launch without failure) but I get another issue with the docker build than you do. My issue trying to replicate that environment seems to be a direct result of my attempt to do things nested in docker. If I have time later in the week I will try some more workarounds to replicate your issue, but so far I cannot replicate it here. I encourage anyone else in the community if they have the means to replicate or confirm this issue to let us know!

**Comment by madhavanpallan** [comment]
Greetings, I was able to replicate the issue and solve it. I installed ubuntu 14.04 on a 32GB flash drive. After installing docker and I did run an example container to check my docker running perfectly. Next step was to run the command "sudo ./BuildDockerImage.sh" it was giving out the issue as mentioned above:-
![issue_Rebuilt](https://user-images.githubusercontent.com/9550258/76023151-9734b100-5ef6-11ea-8de8-056f87d75c61.png)

1) When I ran 'docker build --help', I understood the issue. It was the extra flag value
that we were passing. So, run this command. 
"sudo docker build -f Dockerfile.CLAI -t claiplayground ."

![docker_build_followed_by_run](https://user-images.githubusercontent.com/9550258/76023241-c64b2280-5ef6-11ea-82cc-aa2aee5eb753.png)
Above you can see a container formation, followed by which I ran "sudo ./RunDockerImage.sh" and other instructions remain the same. 
![docker_list](https://user-images.githubusercontent.com/9550258/76023443-335eb800-5ef7-11ea-8467-1eeba9ebc3fe.png)
And finally the testing of CLAI.
![Output](https://user-images.githubusercontent.com/9550258/76023493-47a2b500-5ef7-11ea-9ac1-569b87ffb461.png)
Now, we have a working clai environment in "Ubuntu 14.04". Yay, one more LTS in the list of tested ubuntu O.S.!!

**Comment by TathagataChakraborti** [comment]
Awesome!! @madhavanpallan 👏👏 

@sarathsreedharan can you check once if that works for you?

**Comment by madhavanpallan** [comment]
Thanks @TathagataChakraborti :)
