### ISSUE TITLE
Error with 'Try without installation.'

### ISSUE THREAD

**Issue by andrewcmhicks** [IBM/clai#56]
**Describe the bug**
The `Try without installation.` at https://clai-home.mybluemix.net/ never resolves.

![image](https://user-images.githubusercontent.com/13840294/80440364-9dcc1d00-88d6-11ea-90ab-7f225d1a3cb6.png)

**To Reproduce**
1. Go to 'https://clai-home.mybluemix.net/'
2. Click on 'Try without installation' terminal located to the right of the screen.
3. Enter  'clai skills'
4. The web terminal never responds. 

**Expected behavior**
```
Andrews-MBP-3:clai achicks$ clai skills
Available Skills:
◻ fixit (Not Installed)
◻ helpme (Not Installed)
◻ howdoi (Not Installed)
◻ ibmcloud (Not Installed)
◻ man page explorer (Not Installed)
◻ nlc2cmd (Installed)
◻ onboarding (Not Installed)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/13840294/80440364-9dcc1d00-88d6-11ea-90ab-7f225d1a3cb6.png)

**Log file**
N/A

**shell and OS (please complete the following information):**
 - OS: [Brave Web Browser (Chrome variant)]
 - Shell [N/a]
 - Version [N/A]

**Additional context**
N/A

**Comment by TathagataChakraborti** [comment]
Does this problem disappear if you refresh the page once?

**Comment by TathagataChakraborti** [comment]
@andrewcmhicks can you confirm if you still face this issue?
