### ISSUE TITLE
The keyring library issue while installing in ubuntu 18.04

### ISSUE THREAD

**Issue by madhavanpallan** [IBM/clai#8]
Issue:-
While locally installing clai the keyring library which forms one of the requirements
for some library gives the following error.

![keyring_issue](https://user-images.githubusercontent.com/9550258/73778696-9a9f1600-4759-11ea-9aec-42add7ffe7fb.png)
Error:-
ModuleNotFoundError: No module named "keyring.util.escape"
Screenshot: - https://user-images.githubusercontent.com/9550258/73778696-9a9f1600-4759-11ea-9aec-42add7ffe7fb.png

Solution:- As after keyring version 15.0.0 they removed keyring.util.escape.
It can be solved running "pip3 install --upgrade keyring.alt"
Reference:- https://bugs.launchpad.net/usd-importer/+bug/1794041\

**Comment by flipper83** [comment]
Hi @madhavanpallan did you check the upgrade fix in your machine? and is it working?  I'll going to try to reproduce the bug and the fix. Thank you.

**Comment by madhavanpallan** [comment]
Hi @flipper83, yes I was able to reproduce and apply the solution.

**Comment by flipper83** [comment]
I was checking and the fix crash in Mac. I'm going to check if we can search a fix for all versions
