### ISSUE TITLE
Suggestion: Default password echoed at the end of run docker script.

### ISSUE THREAD

**Issue by madhavanpallan** [IBM/clai#9]
In Ubuntu 18.04 while installing the Docker version and trying to ssh to start clai. It prompts for password. It would be kind to have the default password echoed at the end of docker run.

**Comment by dowem** [comment]
Did we make any progress on this one gents? It seems an easy enough request and it might help usability :)

**Comment by madhavanpallan** [comment]
Changing the last line of RunDockerImage.sh from 
echo 'User for ssh is root and the default pass Bashpass'
to
FGGREEN=`echo "\033[32m"`
echo "${FGGREEN} User for ssh is root and the default pass Bashpass"
highlights the text and supports the cause.
